version: '2'
services:
  preTests:
    command: /myapp/run_tests.sh
    image: 10.100.198.200:5000/rails-ms-tests
    environment:
      - TEST_TYPE=pre
  postTests:
    command: /myapp/run_tests.sh
    image: 10.100.198.200:5000/rails-ms-tests
    environment:
      - TEST_TYPE=post
