version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    command: bundle exec puma -C config/puma.rb
    ports:
      - 8080
   # volumes:
    #  - $PWD:/myapp
    depends_on:
      - migration
    links:
      - db
    image: 10.100.198.200:5000/rails-ms
    environment:
      - SERVICE_NAME=rails-ms
  migration:
    build: .
    image: 10.100.198.200:5000/rails-ms
    command: bin/rake db:migrate RAILS_ENV=development
    environment:
      - SERVICE_NAME=rails-ms
    links:
      - db
    depends_on:
      - db
  preTests:
    image: 10.100.198.200:5000/rails-ms-tests
    environment:
      - TEST_TYPE=pre
    depends_on:
      - migration_tests
    links:
      - db
  postTests:
    image: 10.100.198.200:5000/rails-ms-tests
    environment:
      - TEST_TYPE=post
    depends_on:
      - migration_tests
    links:
      - db
  migration_tests:
    build: .
    image: 10.100.198.200:5000/rails-ms-tests
    command: bin/rake db:migrate RAILS_ENV=test
    environment:
      - SERVICE_NAME=rails-ms
    links:
      - db
    depends_on:
      - db
