version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  base:
    command: bundle exec puma -C config/puma.rb
    ports:
      - 8080
    image: 10.100.198.200:5000/rails-ms
    environment:
      - SERVICE_NAME=rails-ms
  web:
    extends: base
    depends_on:
      - migration
    links:
      - db
  web-blue:
    extends: base
    depends_on:
      - migration
    links:
      - db
    environment:
      - SERVICE_NAME=rails-ms-blue
  web-green:
    extends: base
    depends_on:
      - migration
    links:
      - db
    environment:
      - SERVICE_NAME=rails-ms-green
  migration:
    build: .
    image: 10.100.198.200:5000/rails-ms
    command: bin/rake db:migrate RAILS_ENV=development
    environment:
      - SERVICE_NAME=rails-ms
    links:
      - db
    depends_on:
      - db
  preTests:
    command: /myapp/run_tests.sh
    image: 10.100.198.200:5000/rails-ms-tests
    environment:
      - TEST_TYPE=pre
  postTests:
    command: /myapp/run_tests.sh
    image: 10.100.198.200:5000/rails-ms-tests
    environment:
      - TEST_TYPE=post
