development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  adapter: sqlite3
  database: db/test.sqlite3
  host: 127.0.0.1